account:
  email: ~
  view_id: ~
  key_file: ./client_secrets.p12

metrics:
  - "ga:session"
  - "ga:pageviews"
  - "ga:users"

start_date: "2008-01-01"

scopes:
  - https://www.googleapis.com/auth/analytics.readonly
discovery: !!python/tuple [https://analyticsreporting.googleapis.com/$discovery/rest]

bind_port: 9173
